
name: Staging docker build

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  install-deps-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REPO }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REPO }}:buildcache,mode=max
          
#       - name: Deploy to Staging
#         id: fe
#         uses: actions-hub/kubectl@master
#         env:
#           KUBE_CONFIG: ${{ secrets.DO_PREPROD_KUBECONFIG }}
#         with:
#           args: set image deployment/est-nginx est-nginx=${{ secrets.DOCKER_REPO }}:est-${{ github.sha }} -n int
